import { alpha, colorRamps as c, withAlpha } from './palette';

export type ColorScheme = 'light' | 'dark';
export type ThemeColors = { readonly surface: string; readonly surfaceRaised: string; readonly surfaceSunken: string; readonly surfaceDivider: string; readonly surfaceOverlay: string; readonly textPrimary: string; readonly textSecondary: string; readonly textTertiary: string; readonly textInverted: string; readonly accent: string; readonly accentSoft: string; readonly accentPressed: string; readonly accentOn: string; readonly secondary: string; readonly secondarySoft: string; readonly tertiary: string; readonly tertiarySoft: string; readonly positive: string; readonly negative: string; readonly warning: string; readonly glassTint: string; readonly glassRim: string; readonly glassRimAndroid: string; readonly glassFillAndroid: string; readonly controlActive: string; readonly controlInactive: string; readonly controlTrack: string; readonly scrim: string; readonly skeleton: string; readonly focusRing: string };
export const lightTheme: ThemeColors = { surface: c.paper050, surfaceRaised: c.paper000, surfaceSunken: c.paper100, surfaceDivider: withAlpha(c.basalt800, 0.1), surfaceOverlay: withAlpha(c.paper000, 0.78), textPrimary: c.basalt800, textSecondary: c.basalt500, textTertiary: c.basalt400, textInverted: c.paper000, accent: c.ember500, accentSoft: withAlpha(c.ember400, 0.14), accentPressed: c.ember600, accentOn: c.paper000, secondary: c.damson500, secondarySoft: withAlpha(c.damson400, 0.14), tertiary: c.verdigris500, tertiarySoft: withAlpha(c.verdigris400, 0.14), positive: c.moss500, negative: c.madder500, warning: c.saffron500, glassTint: withAlpha(c.paper050, alpha.medium), glassRim: withAlpha(c.white, alpha.medium), glassRimAndroid: withAlpha(c.basalt800, 0.08), glassFillAndroid: withAlpha(c.paper000, 0.82), controlActive: c.basalt800, controlInactive: withAlpha(c.basalt800, 0.4), controlTrack: c.paper200, scrim: withAlpha(c.basalt900, 0.42), skeleton: withAlpha(c.basalt800, alpha.faint), focusRing: withAlpha(c.ember500, 0.55) };
export const darkTheme: ThemeColors = { surface: c.basalt850, surfaceRaised: c.basalt750, surfaceSunken: c.basalt900, surfaceDivider: withAlpha(c.paper000, 0.1), surfaceOverlay: withAlpha(c.basalt800, 0.78), textPrimary: c.paper050, textSecondary: c.basalt200, textTertiary: c.basalt300, textInverted: c.basalt900, accent: c.ember400, accentSoft: withAlpha(c.ember300, 0.18), accentPressed: c.ember300, accentOn: c.basalt900, secondary: c.damson300, secondarySoft: withAlpha(c.damson300, 0.18), tertiary: c.verdigris300, tertiarySoft: withAlpha(c.verdigris300, 0.16), positive: c.moss300, negative: c.madder300, warning: c.saffron300, glassTint: withAlpha(c.basalt800, 0.55), glassRim: withAlpha(c.paper000, 0.14), glassRimAndroid: withAlpha(c.paper000, 0.1), glassFillAndroid: withAlpha(c.basalt750, 0.88), controlActive: c.paper050, controlInactive: withAlpha(c.paper050, 0.38), controlTrack: c.basalt700, scrim: withAlpha(c.basalt900, 0.62), skeleton: withAlpha(c.paper000, 0.08), focusRing: withAlpha(c.ember300, 0.6) };
export const themes: Readonly<Record<ColorScheme, ThemeColors>> = { light: lightTheme, dark: darkTheme };
export type SceneColors = { readonly background: string; readonly surfaceBase: string; readonly surfaceDeep: string; readonly surfaceBreath: string; readonly surfaceGrid: string; readonly surfaceDot: string; readonly shadow: string; readonly keyLight: string; readonly fillLight: string; readonly fireCore: string; readonly fireCoreEmissive: string; readonly fireShell: string; readonly fireEmissive: string; readonly fireLight: string; readonly cloudBody: string; readonly cloudEdge: string; readonly selection: string };
const FIRE = { fireCore: '#EE9412', fireCoreEmissive: '#FF8A1F', fireShell: '#FE4F00', fireEmissive: '#FF8A1F', fireLight: '#FEC200' } as const;
export const lightScene: SceneColors = { background: '#F7F4ED', surfaceBase: '#EDE7DA', surfaceDeep: '#D9D1C0', surfaceBreath: '#FFF3DE', surfaceGrid: '#ECE9E1', surfaceDot: '#CFC7B5', shadow: '#A79E8B', keyLight: '#FFF6E8', fillLight: '#D7DEE8', ...FIRE, cloudBody: c.slate300, cloudEdge: c.slate500, selection: c.ember300 };
export const darkScene: SceneColors = { background: '#121017', surfaceBase: '#1A1720', surfaceDeep: '#0E0C12', surfaceBreath: '#3A2A1C', surfaceGrid: '#221E2A', surfaceDot: '#332D3E', shadow: '#07060A', keyLight: '#FFE7C2', fillLight: '#4A5566', ...FIRE, cloudBody: c.slate500, cloudEdge: c.slate300, selection: c.ember300 };
export const sceneThemes: Readonly<Record<ColorScheme, SceneColors>> = { light: lightScene, dark: darkScene };
